# Generated by Django 5.1.6 on 2025-03-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0003_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": (
                    ("add", "can_add_book"),
                    ("change", "can_change_book"),
                    ("delete", "can_delete_book"),
                )
            },
        ),
    ]
