# Generated by Django 5.1.6 on 2025-03-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Librarian", "Librarian"),
                    ("Member", "Member"),
                ],
                default="Member",
                max_length=10,
            ),
        ),
    ]
